config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/home', to: 'static_pages#home', via: 'get'
  match '/signup', to: 'users#new', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
	validates :name, presence: true, length: { maximum: 50 }
	validates :password, length: { minimum: 6 }
	validates :email, presence: true, uniqueness: { case_sensetive: false }, format: { whith: "/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i" }
	before_save { self.email = email.downcase }
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom">
	<small>
		Система электронного журнала
	</small>
	<nav>
				<ul class="nav navbar-right navbar-nav">
					<li class="<%= "active" if params[:action] == "home" %>"><%= link_to "Домашняя страница", "#"%></li>
					<li class="<%= "active" if params[:action] == "about" %>"><%= link_to "О проекте", "#"%></li>
					<li><%= link_to "Войти", "#" %></li>
				</nav>
</footer>

app/views/layouts/_menu.html.erb
<header class="navbar navbar-default ">
	<div class="navbar-inner">
		<div class="container">
			<img alt="Электронный Журнал" src="/assets/rails.png" class="navbar-brand"/>
			<nav>
				<ul class="nav nav-tabs">
					<li class="<%= "active" if params[:action] == "home" %>"><%= link_to "Домашняя страница", home_path%></li>
					<li class="<%= "active" if params[:action] == "about" %>"><%= link_to "О проекте", about_path%></li>
					<li class="<%= "active" if params[:action] == "new" %>"><%= link_to "Регистрация", signup_path%></li>
				</nav>
		</div>
	</div> 
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		  <title>Электронный журнал | <%= yield(:title) %></title>
		  <% render 'layouts/shim' %>
		  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/menu' %>
		<div class="container">
			<%= yield %>
		</div>
	</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "О проекте") %>

<h1>Электронный журнал</h1>
<p>
	Простой пример электронного журнала
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Домашняя страница") %>
<div class="center jumbotron">
	<h1>
		Добро пожаловать в cиситему электронного журнала
		<br>
	</h1>
	<h2>
		<small>Это домашняя страницы системы электронного журнала</small>
	</h2>
	<br>
	<%= link_to "Регистрация", signup_path, class: "btn btn-lg btn-primary center" %>
</div>

app/views/users/new.html.erb
<% provide(:title, "Регистрация") %>